---
abstract: 'Class::Accessor::Fast with lazy defaults'
author:
  - 'Jan Henning Thorsen C<< jhthorsen at cpan.org >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.9
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-Accessor-Fast-WithBuilder
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor: 0.32
  base: 2.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Accessor-Fast-WithBuilder
  homepage: http://search.cpan.org/dist/Class-Accessor-Fast-WithBuilder
version: 0.01
